FROM python:3.9.6

WORKDIR /app 

COPY ./ app 

RUN pip install --no-cache-dir Flask==2.1.1 Flask-SQLAlchemy==2.4 SQLAlchemy==1.3.24 Werkzeug==2.0.0 pymysql

EXPOSE 5001

CMD ["python", "read_service.py"] 